### ISSUE TITLE
[bug] br_bd_metadados.tables - erro na pipeline

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/pipelines#267]
Em 23/12/2022 a flow reportou o seguinte erro:
```
Task 'crawler_tables': Exception encountered during task execution!
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/opt/venv/lib/python3.9/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pipelines/datasets/br_bd_metadados/tasks.py", line 390, in crawler_tables
UnboundLocalError: local variable 'number_rows' referenced before assignment
```
Verificar e corrigir, se for uma falha, ou tratar o erro.

**Comment by mfagundes** [comment]
Após abrir a issue, rodei manualmente. Foram duas tentativas (a primeira ficou parada, sem concluir ou apresentar erro) e a segunda rodou normalmente em 43 segundos. Ou seja, provavelmente há um erro que não está sendo tratado
