### ISSUE TITLE
[infra] FGV - Erro no pacote Ipeadata.py quebra a pipeline

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/pipelines#277]
Em 08/02/2-23, na atualização mensal do índice IGP-OG mensal (`IGP12_IGPOG12`), o pacote `ipeadatapy` passou a dar um erro, possivelmente devido a alguma altração na API do Ipea. 

- ipeadatapy: https://github.com/luanborelli/ipeadatapy
- Documentação da API do Ipea: https://www.ipea.gov.br/portal/mestrado-profissional-em-politicas-publicas-e-desenvolvimentodesafios/index.php?option=com_content&view=article&id=1825:catid=28&Itemid=23

Erro:
```
Task 'crawler_fgv': Exception encountered during task execution!
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/opt/venv/lib/python3.9/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pipelines/datasets/br_fgv_igp/tasks.py", line 27, in crawler_fgv
  File "/opt/venv/lib/python3.9/site-packages/pipelines/datasets/br_fgv_igp/utils.py", line 27, in __init__
    self.df = self._create_dataframe()
  File "/opt/venv/lib/python3.9/site-packages/pipelines/datasets/br_fgv_igp/utils.py", line 52, in _create_dataframe
    df = self._get_ipea_data()
  File "/opt/venv/lib/python3.9/site-packages/pipelines/datasets/br_fgv_igp/utils.py", line 44, in _get_ipea_data
    return idpy.timeseries(self.main_index)
  File "/opt/venv/lib/python3.9/site-packages/ipeadatapy/timeseries.py", line 53, in timeseries
    ts_df = api_call(api)[['ANO','DIA','MES','SERCODIGO','VALDATA','VALVALOR']].rename(index=str, columns={"ANO": "YEAR", "DIA": "DAY", "MES": "MONTH", "SERCODIGO": "CODE", "VALDATA": "DATE", "VALVALOR": "VALUE ("+list(metadata_old(series)['MEASURE'])[0]+")"})
TypeError: 'NoneType' object is not subscriptable
```

Testado diretamente em um Jupyter Notebook, o erro persiste. O endpoint `[Valores](http://www.ipeadata.gov.br/api/odata4/Valores)` da API do Ipea retorna o seguinte erro:
`No HTTP resource was found that matches the request URI 'http://ipeadata.gov.br/api/odata4/Valores`

Os demais estão funcionando.

**Comment by mfagundes** [comment]
Parei, temporariamente, as seguintes pipelines:
- IGP-10 mensal
- IGP-DI anual
- IGP-DI mensal
- IGP-M anual
- IGP-M mensal
- IGP-OG anual
- IGP-OG mensal
